import { DecisionLayer } from './layer-decision-support.models';

export const LAYER_CATALOG: readonly DecisionLayer[] = [
  {
    id: 'property-boundaries',
    title: 'Fastighetsgränser',
    summary: 'Fastighetsgränser med registerbaserad referensinformation.',
    category: 'Fastighet',
    renderOrder: 10,
    projection: 'EPSG:3006',
    restricted: false,
    quality: {
      score: 96,
      updatedAt: '2026-05-31T08:00:00.000Z',
      source: 'Kvalitetssäkrat fastighetsutdrag',
      srid: 'EPSG:3006',
    },
    exportFormats: ['pdf', 'xlsx', 'docx'],
  },
  {
    id: 'climate-risk',
    title: 'Klimatriskzoner',
    summary: 'Riskklassning för översvämning och värme i beslutsunderlag.',
    category: 'Klimat',
    renderOrder: 30,
    projection: 'EPSG:3006',
    restricted: false,
    quality: {
      score: 88,
      updatedAt: '2026-04-20T08:00:00.000Z',
      source: 'Kommunal planeringsmodell',
      srid: 'EPSG:3006',
    },
    exportFormats: ['pdf', 'xlsx'],
  },
  {
    id: 'protected-imagery',
    title: 'Skyddad flygbild',
    summary: 'Högupplöst flygbild som kräver utökad geodatabehörighet.',
    category: 'Flygbild',
    renderOrder: 20,
    projection: 'EPSG:3857',
    restricted: true,
    requiredRole: 'restricted-geodata',
    quality: {
      score: 91,
      updatedAt: '2026-06-01T08:00:00.000Z',
      source: 'Begränsat bildarkiv',
      srid: 'EPSG:3857',
    },
    exportFormats: ['pdf'],
  },
  {
    id: 'utility-corridors',
    title: 'Ledningsstråk',
    summary: 'Indikativa korridordata för granskning av infrastruktur.',
    category: 'Infrastruktur',
    renderOrder: 40,
    projection: 'EPSG:3006',
    restricted: true,
    requiredRole: 'restricted-geodata',
    quality: {
      score: 74,
      updatedAt: '2026-03-12T08:00:00.000Z',
      source: 'Partnerflöde för infrastruktur',
      srid: 'EPSG:3006',
    },
    exportFormats: ['xlsx'],
  },
];
